package xapi.dev.ui.api;

import com.github.javaparser.ast.expr.UiContainerExpr;
import xapi.dev.api.ApiGeneratorContext;
import xapi.dev.ui.impl.AbstractUiGeneratorService;
import xapi.dev.ui.impl.UiGeneratorTools;
import xapi.dev.ui.impl.InterestingNodeFinder.InterestingNodeResults;
import xapi.dev.ui.api.UiComponentGenerator.UiGenerateMode;

/**
 * Instances of a {@link UiImplementationGenerator} are responsible
 * for generating platform-specific implementations which extend
 * a common generic superclass generated by {@link UiGeneratorService}.
 *
 * It is expected that multiple instances of these generators
 * could be run in a single compilation, so care should be
 * taken to not mutate any shared state.
 *
 * Created by James X. Nelson (james @wetheinter.net) on 6/28/16.
 */
public interface UiImplementationGenerator {

    String getImplName(String pkgName, String className);

    UiGeneratorService getGenerator();

    UiGeneratorTools getTools();

    GeneratedUiImplementation generateComponent(
        ContainerMetadata metadata,
        ComponentBuffer buffer,
        UiGenerateMode mode
    );

    default ContainerMetadata createMetadata(MetadataRoot root, UiContainerExpr n) {
        return getTools().createMetadata(root, n);
    }

    void setGenerator(UiGeneratorService service);

    void spyOnInterestingNodes(ComponentBuffer component, InterestingNodeResults interestingNodes);

    void spyOnNewComponent(ComponentBuffer component);

    GeneratedUiImplementation getImpl(GeneratedUiComponent component);

    UiGenerateMode getMode(ComponentBuffer component, ContainerMetadata metadata);

}
