package xapi.dev.ui.api;

import net.wti.lang.parser.ast.expr.UiContainerExpr;
import xapi.dev.ui.api.UiComponentGenerator.UiGenerateMode;
import xapi.dev.ui.impl.InterestingNodeFinder.InterestingNodeResults;

/**
 * Instances of a {@link UiImplementationGenerator} are responsible
 * for generating platform-specific implementations which extend
 * a common generic superclass generated by {@link UiGeneratorService}.
 *
 * It is expected that multiple instances of these generators
 * could be run in a single compilation, so care should be
 * taken to not mutate any shared state.
 *
 * Created by James X. Nelson (james @wetheinter.net) on 6/28/16.
 */
public interface UiImplementationGenerator extends ImplementationGenerator <GeneratedUiComponent, GeneratedUiImplementation> {

    GeneratedUiImplementation generateComponent(
        ContainerMetadata metadata,
        ComponentBuffer buffer,
        UiGenerateMode mode
    );

    default ContainerMetadata createMetadata(MetadataRoot root, UiContainerExpr n) {
        return getTools().createMetadata(root, n);
    }

    void setGenerator(UiGeneratorService service);

    void spyOnInterestingNodes(ComponentBuffer component, InterestingNodeResults interestingNodes);

    void spyOnNewComponent(ComponentBuffer component);

    UiGenerateMode getMode(ComponentBuffer component, ContainerMetadata metadata);

}
